"""
UC-0B — Policy Summariser
Usage:
    python app.py --input ../data/policy-documents/policy_hr_leave.txt --output summary_hr_leave.txt

Reads a numbered HR policy document and produces a faithful summary where:
  - Every numbered clause is present
  - All multi-condition obligations are fully preserved
  - No information is added beyond what the source document states
  - Clauses that cannot be summarised without meaning loss are quoted verbatim and flagged
"""

import argparse
import re
import sys
import os


# ── Skill: retrieve_policy ────────────────────────────────────────────────────

def retrieve_policy(filepath: str) -> list[dict]:
    """
    Loads a .txt policy file and returns content parsed into structured,
    numbered sections.
    Returns: list of {"section": "2.3", "text": "..."} dicts.
    """
    if not os.path.isfile(filepath):
        print(f"ERROR: File not found: {filepath}", file=sys.stderr)
        sys.exit(1)

    with open(filepath, "r", encoding="utf-8") as f:
        raw = f.read()

    sections = []
    # Match patterns like "2.3 Employees must..." across lines
    pattern = re.compile(
        r'(?m)^[ \t]*(\d+\.\d+)[ \t]+(.*?)(?=\n[ \t]*\d+\.\d+|\n[ \t]*[═=]{5}|\Z)',
        re.DOTALL
    )
    for match in pattern.finditer(raw):
        section_num = match.group(1).strip()
        # Collapse continuation lines (indented continuation)
        text = re.sub(r'\n[ \t]+', ' ', match.group(2)).strip()
        sections.append({"section": section_num, "text": text})

    return sections


# ── Skill: summarize_policy ────────────────────────────────────────────────────

# Clauses that must NEVER be paraphrased (high condition-drop risk)
VERBATIM_CLAUSES = {"5.2", "5.3", "7.2"}

def summarize_policy(sections: list[dict], output_path: str):
    """
    Takes structured sections from retrieve_policy, writes a compliant summary
    to output_path.  Every clause is referenced by number.  Clauses in
    VERBATIM_CLAUSES are quoted word-for-word and flagged.
    """
    lines = []
    lines.append("POLICY SUMMARY — HR Leave Policy (HR-POL-001)")
    lines.append("=" * 60)
    lines.append("Generated by UC-0B Policy Summariser")
    lines.append("Source only — no external information added.")
    lines.append("=" * 60)
    lines.append("")

    current_section_header = None

    # Section heading map (derived from document structure)
    section_headers = {
        "1": "1. PURPOSE AND SCOPE",
        "2": "2. ANNUAL LEAVE",
        "3": "3. SICK LEAVE",
        "4": "4. MATERNITY AND PATERNITY LEAVE",
        "5": "5. LEAVE WITHOUT PAY (LWP)",
        "6": "6. PUBLIC HOLIDAYS",
        "7": "7. LEAVE ENCASHMENT",
        "8": "8. GRIEVANCES",
    }

    for entry in sections:
        sec = entry["section"]
        top = sec.split(".")[0]

        # Print section header when we enter a new top-level section
        if top != current_section_header:
            current_section_header = top
            header = section_headers.get(top, f"{top}.")
            lines.append("")
            lines.append(header)
            lines.append("-" * 40)

        if sec in VERBATIM_CLAUSES:
            lines.append(f"  {sec}  [VERBATIM — condition-drop risk]")
            lines.append(f"       \"{entry['text']}\"")
            lines.append(f"       ⚑ flag: VERBATIM_REQUIRED")
        else:
            lines.append(f"  {sec}  {entry['text']}")

    lines.append("")
    lines.append("=" * 60)
    lines.append(f"Total clauses summarised: {len(sections)}")

    summary = "\n".join(lines)

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(summary)

    print(f"Done. {len(sections)} clauses written → {output_path}")


# ── CLI entry point ────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="UC-0B — Policy Summariser: produces a faithful clause-level summary."
    )
    parser.add_argument("--input",  required=True, help="Path to input .txt policy file")
    parser.add_argument("--output", required=True, help="Path to output summary .txt file")
    args = parser.parse_args()

    sections = retrieve_policy(args.input)
    if not sections:
        print("ERROR: No numbered clauses found in the document.", file=sys.stderr)
        sys.exit(1)

    summarize_policy(sections, args.output)


if __name__ == "__main__":
    main()
