import argparse
import os
import re

def retrieve_policy(input_file):
    """
    Parses a text file into numbered clauses.
    Looks for lines starting with X.X pattern.
    """
    if not os.path.exists(input_file):
        raise FileNotFoundError(f"Policy file not found: {input_file}")
    
    with open(input_file, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Regex to find sections like 2.3, 5.2, etc.
    # It looks for digits followed by a dot and digits at the start of a line block.
    sections = re.split(r'\n(?=\d+\.\d+)', content)
    
    clauses = []
    for section in sections:
        match = re.match(r'(\d+\.\d+)\s+(.*)', section.strip(), re.DOTALL)
        if match:
            clauses.append({
                "clause": match.group(1),
                "content": match.group(2).replace('\n', ' ').strip()
            })
    return clauses

def summarize_policy(clauses):
    """
    Summarizes specific key clauses while preserving binding obligations.
    """
    target_clauses = {
        "2.3": "14-day advance notice required using Form HR-L1.",
        "2.4": "Written approval from direct manager REQUIRED before leave begins. Verbal approval is NOT valid.",
        "2.5": "Unapproved absence = Loss of Pay (LOP) regardless of subsequent approval.",
        "2.6": "Max 5 days carry-forward. Excess days are forfeited on 31 Dec.",
        "2.7": "Carry-forward days must be used in Q1 (Jan–Mar) or forfeited.",
        "3.2": "3+ consecutive sick days requires a medical certificate submitted within 48 hours of return.",
        "3.4": "Sick leave before/after a holiday or annual leave requires a medical certificate regardless of duration.",
        "5.2": "LWP requires approval from BOTH the Department Head and HR Director. Manager approval is insufficient.",
        "5.3": "LWP > 30 days requires Municipal Commissioner approval.",
        "7.2": "Leave encashment during service is NOT PERMITTED under any circumstances."
    }
    
    summary_lines = []
    summary_lines.append("CITY MUNICIPAL CORPORATION - HR LEAVE POLICY SUMMARY")
    summary_lines.append("=" * 60)
    summary_lines.append("")
    
    found_clauses = {c['clause']: c['content'] for c in clauses}
    
    for cid, rule in target_clauses.items():
        if cid in found_clauses:
            summary_lines.append(f"[{cid}] {rule}")
        else:
            summary_lines.append(f"[{cid}] WARNING: Clause not found in source document.")
            
    summary_lines.append("")
    summary_lines.append("Generated by Policy Compliance Analyst Agent.")
    
    return "\n".join(summary_lines)

def main():
    parser = argparse.ArgumentParser(description="UC-0B Policy Summarizer")
    parser.add_argument("--input", required=True, help="Path to the policy text file")
    parser.add_argument("--output", required=True, help="Path to save the summary")
    
    args = parser.parse_args()
    
    try:
        clauses = retrieve_policy(args.input)
        summary = summarize_policy(clauses)
        
        with open(args.output, 'w', encoding='utf-8') as f:
            f.write(summary)
            
        print(f"Summary successfully generated: {args.output}")
        
    except Exception as e:
        print(f"Error: {str(e)}")

if __name__ == "__main__":
    main()
