"""
UC-0B: Summary That Changes Meaning
====================================
Reads HR policy documents and produces faithful, complete summaries
using an LLM — enforcing completeness and meaning-preservation.

Usage:
    python app.py

Output:
    summary_hr_leave.txt
"""

import os
import re
import json
from datetime import date
from anthropic import Anthropic

# ── Config ──────────────────────────────────────────────────────────────────
POLICY_FILE = os.path.join(
    os.path.dirname(__file__), "..", "data", "policy-documents", "policy_hr_leave.txt"
)
OUTPUT_FILE = os.path.join(os.path.dirname(__file__), "summary_hr_leave.txt")

client = Anthropic()

# ── Skill 1: read_policy_document ────────────────────────────────────────────
def read_policy_document(filepath: str) -> str:
    """Load and return the full text of a policy document."""
    if not os.path.exists(filepath):
        raise FileNotFoundError(f"Policy file not found: {filepath}")
    with open(filepath, "r", encoding="utf-8") as f:
        text = f.read().strip()
    if not text:
        raise ValueError("Policy document is empty.")
    print(f"[✓] Loaded policy document: {filepath} ({len(text)} chars)")
    return text


# ── Skill 2: count_clauses ───────────────────────────────────────────────────
def count_clauses(text: str) -> int:
    """Count numbered clauses/sections in the source document."""
    patterns = [
        r"^\s*\d+[\.\)]\s",          # 1. or 1)
        r"^\s*\(\s*[a-zA-Z\d]+\s*\)",# (a) or (1)
        r"^\s*[Ss]ection\s+\d+",     # Section 1
        r"^\s*[Cc]lause\s+\d+",      # Clause 1
        r"^\s*[Aa]rticle\s+\d+",     # Article 1
    ]
    combined = re.compile("|".join(patterns), re.MULTILINE)
    matches = combined.findall(text)
    count = len(matches)
    print(f"[✓] Detected {count} clauses/sections in source document.")
    return count


# ── Skill 3: summarise_with_llm ──────────────────────────────────────────────
SYSTEM_PROMPT = """You are a precise HR policy summarisation specialist working for a civic organisation.
Your summaries are relied upon legally by employees and HR administrators.
An inaccurate summary creates real harm — employees may lose entitlements or face penalties they were unaware of.

STRICT RULES — violating any of these is a failure:
1. Every numbered clause in the source document MUST appear in the summary.
2. Obligations (must, shall, will not) must remain obligations — never soften to "should" or "may".
3. Penalties must not be softened — "termination" stays "termination".
4. Do NOT merge clauses that have different conditions or timeframes.
5. Do NOT invent or add any information not in the source.
6. Do NOT skip exceptions, eligibility conditions, or deadlines.
7. Mark any clause containing a condition, exception, penalty, or deadline with [CONDITION].

OUTPUT FORMAT:
POLICY SUMMARY: {title}
Generated by: PolicySummaryAgent
Date: {today}

---

Then, for each section/clause in order:
CLAUSE [N]: [short title if available]
[Your faithful summary of the clause — 1-3 sentences]
[CONDITION] if applicable

---
COMPLETENESS CHECK:
- Clauses identified in source: [N]
- Clauses covered in summary: [N]
- Status: PASS or FAIL
"""

def summarise_with_llm(policy_text: str, title: str = "HR Leave Policy") -> str:
    """Send policy text to Claude and get a complete, faithful summary."""
    system = SYSTEM_PROMPT.replace("{title}", title).replace("{today}", str(date.today()))

    print("[→] Sending policy to LLM for summarisation...")
    response = client.messages.create(
        model="claude-opus-4-5",
        max_tokens=4096,
        system=system,
        messages=[
            {
                "role": "user",
                "content": (
                    f"Please summarise the following HR policy document faithfully and completely.\n\n"
                    f"Document title: {title}\n\n"
                    f"---\n\n{policy_text}"
                ),
            }
        ],
    )
    summary = response.content[0].text
    print(f"[✓] Summary generated ({len(summary)} chars).")
    return summary


# ── Skill 4: verify_completeness ─────────────────────────────────────────────
def verify_completeness(source_clause_count: int, summary: str) -> bool:
    """Check that the summary's completeness check shows PASS."""
    # Look for explicit PASS/FAIL in the summary
    if "Status: PASS" in summary or "PASS" in summary.upper().split("STATUS:")[-1][:20]:
        print("[✓] Completeness check: PASS")
        return True
    if "Status: FAIL" in summary or "FAIL" in summary.upper().split("STATUS:")[-1][:20]:
        print("[✗] Completeness check: FAIL — summary may be missing clauses.")
        return False
    # Fallback: count [CLAUSE markers in summary
    summary_clauses = len(re.findall(r"CLAUSE\s+\d+", summary, re.IGNORECASE))
    if summary_clauses >= source_clause_count:
        print(f"[✓] Completeness check: {summary_clauses}/{source_clause_count} clauses covered.")
        return True
    print(
        f"[⚠] Completeness check: only {summary_clauses}/{source_clause_count} "
        f"clauses detected in summary. Consider reviewing."
    )
    return False


# ── Skill 5: detect_meaning_drift ────────────────────────────────────────────
DRIFT_PATTERNS = [
    (r"\bshould submit\b", "may have originally said 'must submit'"),
    (r"\bmay face\b", "may have originally said 'will be terminated'"),
    (r"\bencouraged to\b", "may have originally said 'required to'"),
    (r"\bconsider\b", "may have originally said 'must'"),
    (r"\bgenerally\b", "softens a specific rule"),
    (r"\betc\b\.?", "may omit items from a complete list"),
    (r"\bsome cases\b", "may soften an absolute rule"),
    (r"\btypically\b", "softens a mandatory requirement"),
]

def detect_meaning_drift(summary: str) -> list:
    """Scan summary for phrases that indicate meaning has been softened."""
    warnings = []
    lines = summary.split("\n")
    for i, line in enumerate(lines, start=1):
        for pattern, reason in DRIFT_PATTERNS:
            if re.search(pattern, line, re.IGNORECASE):
                warnings.append(f"[DRIFT WARNING] Line {i}: '{pattern}' — {reason}")
    if warnings:
        print(f"[⚠] {len(warnings)} potential meaning-drift warning(s) detected.")
        for w in warnings:
            print(f"    {w}")
    else:
        print("[✓] No meaning-drift patterns detected.")
    return warnings


# ── Skill 6: write_summary_file ──────────────────────────────────────────────
def write_summary_file(summary: str, output_path: str) -> None:
    """Write the final summary to disk."""
    os.makedirs(os.path.dirname(output_path) if os.path.dirname(output_path) else ".", exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(summary)
    print(f"[✓] Summary written to: {output_path} ({len(summary)} chars)")


# ── Optional: re-prompt if completeness fails ────────────────────────────────
def repair_summary(policy_text: str, original_summary: str, source_clause_count: int, title: str) -> str:
    """If summary failed completeness check, ask Claude to fix it."""
    print("[→] Requesting completeness repair from LLM...")
    response = client.messages.create(
        model="claude-opus-4-5",
        max_tokens=4096,
        system=(
            "You are a precise HR policy summarisation specialist. "
            "Your previous summary missed some clauses. "
            "You MUST include every numbered clause from the source. "
            "Return only the corrected full summary — no preamble."
        ),
        messages=[
            {
                "role": "user",
                "content": (
                    f"The original policy had {source_clause_count} clauses. "
                    f"Your previous summary appears to have missed some.\n\n"
                    f"Original policy:\n---\n{policy_text}\n---\n\n"
                    f"Previous summary:\n---\n{original_summary}\n---\n\n"
                    f"Please produce a corrected, complete summary now."
                ),
            }
        ],
    )
    repaired = response.content[0].text
    print(f"[✓] Repaired summary generated ({len(repaired)} chars).")
    return repaired


# ── Main pipeline ────────────────────────────────────────────────────────────
def main():
    print("\n" + "=" * 60)
    print("  UC-0B: Summary That Changes Meaning")
    print("  PolicySummaryAgent — CRAFT loop")
    print("=" * 60 + "\n")

    # Step 1: Read policy
    policy_text = read_policy_document(POLICY_FILE)

    # Step 2: Count source clauses
    source_clause_count = count_clauses(policy_text)

    # Extract title from first line if possible
    first_line = policy_text.split("\n")[0].strip()
    title = first_line if len(first_line) < 80 else "HR Leave Policy"

    # Step 3: Summarise
    summary = summarise_with_llm(policy_text, title=title)

    # Step 4: Check for meaning drift
    drift_warnings = detect_meaning_drift(summary)

    # Step 5: Verify completeness
    passed = verify_completeness(source_clause_count, summary)

    # Step 6: Repair if needed (CRAFT — refine loop)
    if not passed:
        summary = repair_summary(policy_text, summary, source_clause_count, title)
        # Append drift warnings to summary if any
        if drift_warnings:
            summary += "\n\n---\nDRIFT WARNINGS DETECTED DURING REVIEW:\n"
            summary += "\n".join(drift_warnings)

    # Step 7: Write output
    write_summary_file(summary, OUTPUT_FILE)

    print("\n" + "=" * 60)
    print("  ✅ UC-0B complete. Output: summary_hr_leave.txt")
    print("=" * 60 + "\n")


if __name__ == "__main__":
    main()
