"""
UC-0A — Complaint Classifier
Generated by Antigravity based on agents.md and skills.md RICE rules.
"""
import argparse
import csv

URGENT_KEYWORDS = ['injury', 'child', 'school', 'hospital', 'ambulance', 'fire', 'hazard', 'fell', 'collapse']

CATEGORY_KEYWORDS = {
    "Pothole": ["pothole"],
    "Flooding": ["flood", "flooded", "floods", "rain"],
    "Drain Blockage": ["drain blocked", "drain", "clogged"],
    "Streetlight": ["streetlight", "lights out", "dark", "light", "lights"],
    "Waste": ["garbage", "waste", "dead animal", "dumped", "smell"],
    "Noise": ["music", "noise", "loud"],
    "Road Damage": ["crack", "sinking", "manhole", "footpath", "surface", "tiles"],
    "Heritage Damage": ["heritage damage", "monument"],
    "Heat Hazard": ["heat hazard", "heatwave", "temperature"],
}

def classify_complaint(row: dict) -> dict:
    """
    Classify a single complaint row into category, priority, reason, and flag.
    """
    description = row.get("description", "").lower()
    
    category = "Other"
    priority = "Standard"
    flag = ""
    reason_kw = ""
    priority_kw = ""

    # Priority Evaluation
    for kw in URGENT_KEYWORDS:
        if kw in description:
            priority = "Urgent"
            priority_kw = kw
            break

    # Category Evaluation
    found_category = False
    
    # Handle overlap edges manually based on context
    if "pothole" in description:
        category = "Pothole"
        reason_kw = "pothole"
        found_category = True
    elif "drain" in description:
        category = "Drain Blockage"
        reason_kw = "drain"
        found_category = True
    elif "flood" in description or "water" in description:
        category = "Flooding"
        reason_kw = "flood" if "flood" in description else "water"
        found_category = True
        
    if not found_category:
        for cat, keywords in CATEGORY_KEYWORDS.items():
            for kw in keywords:
                if kw in description:
                    category = cat
                    reason_kw = kw
                    found_category = True
                    break
            if found_category:
                break

    # Specific override for tricky cases (e.g. heritage vs streetlight)
    if "heritage street" in description and "lights out" in description:
        category = "Streetlight"
        reason_kw = "lights out"

    # Set reason and review flag
    if category == "Other":
        flag = "NEEDS_REVIEW"
        reason = "Category is genuinely ambiguous; description lacks identifiable keywords."
    else:
        if priority == "Urgent":
            reason = f"Classified as {category} due to '{reason_kw}', escalated to Urgent due to '{priority_kw}'."
        else:
            reason = f"Classified as {category} because description mentions '{reason_kw}'."

    return {
        "complaint_id": row.get("complaint_id", "UNKNOWN"),
        "category": category,
        "priority": priority,
        "reason": reason,
        "flag": flag
    }

def batch_classify(input_path: str, output_path: str):
    """
    Read input CSV, classify each row, and write to output CSV.
    """
    with open(input_path, 'r', encoding='utf-8') as infile, \
         open(output_path, 'w', newline='', encoding='utf-8') as outfile:
        
        reader = csv.DictReader(infile)
        
        fieldnames = ["complaint_id", "category", "priority", "reason", "flag"]
        writer = csv.DictWriter(outfile, fieldnames=fieldnames)
        writer.writeheader()
        
        for row in reader:
            # Handle empty/null rows robustly
            if not row or (not row.get("complaint_id") and not row.get("description")):
                continue
                
            try:
                result = classify_complaint(row)
                writer.writerow(result)
            except Exception as e:
                print(f"Error processing row {row.get('complaint_id')}: {e}")
                # Write an error indicator for this row so we don't drop it purely on fail
                writer.writerow({
                    "complaint_id": row.get("complaint_id", "UNKNOWN"),
                    "category": "Other",
                    "priority": "Low",
                    "reason": f"System error processing row: {str(e)}",
                    "flag": "NEEDS_REVIEW"
                })

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="UC-0A Complaint Classifier")
    parser.add_argument("--input",  required=True, help="Path to test_[city].csv")
    parser.add_argument("--output", required=True, help="Path to write results CSV")
    args = parser.parse_args()
    batch_classify(args.input, args.output)
    print(f"Done. Results written to {args.output}")
