"""
UC-0A — Complaint Classifier
Generated by AI coding assistant based on agents.md and skills.md.
"""
import argparse
import csv

def classify_complaint(row: dict) -> dict:
    """
    Classify a single complaint row based on the defined context and enforcement rules.
    Returns: dict with keys: complaint_id, category, priority, reason, flag
    """
    description = row.get("description", "").lower()
    
    # 1. Enforcement rule: Category must be exactly one of the defined list
    # Keyword mapping for categories
    cat_rules = {
        'Pothole': ['pothole'],
        'Flooding': ['flood'],
        'Streetlight': ['streetlight', 'lights out'],
        'Waste': ['waste', 'garbage', 'dead animal'],
        'Noise': ['noise', 'music'],
        'Road Damage': ['cracked', 'footpath', 'manhole', 'road damage', 'broken'],
        'Heritage Damage': ['heritage'],
        'Heat Hazard': ['heat'],
        'Drain Blockage': ['drain block']
        # 'Other' is default
    }
    
    matched_cats = {}
    for cat, kws in cat_rules.items():
        for kw in kws:
            if kw in description:
                matched_cats.setdefault(cat, []).append(kw)
                
    cat_evidence = ""
    # Refusal condition / Ambiguity handling
    if not matched_cats:
        category = "Other"
        flag = ""
    elif len(matched_cats) == 1:
        category = list(matched_cats.keys())[0]
        flag = ""
        cat_evidence = matched_cats[category][0]
    else:
        # Genuinely ambiguous (multiple categories matched)
        category = "Other"
        flag = "NEEDS_REVIEW"
        cat_evidence = "multiple conflicting signals"

    # 2. Enforcement rule: Priority must be Urgent if description contains severity keywords
    urgent_keywords = ['injury', 'child', 'school', 'hospital', 'ambulance', 'fire', 'hazard', 'fell', 'collapse']
    
    priority_evidence = None
    for kw in urgent_keywords:
        if kw in description:
            priority_evidence = kw
            break
            
    if priority_evidence:
        priority = "Urgent"
    else:
        priority = "Standard"
        
    # 3. Enforcement rule: Every output row must include a reason field citing specific words
    reasons = []
    if cat_evidence and cat_evidence != "multiple conflicting signals":
        reasons.append(f"mentions '{cat_evidence}'")
    else:
        reasons.append("description lacks clear single-category keywords")
        
    if priority_evidence:
        reasons.append(f"and contains severity keyword '{priority_evidence}'")
        
    reason = f"Classified as {category} with {priority} priority because the text {' '.join(reasons)}."
    reason = reason.replace("  ", " ").strip()
    
    return {
        "complaint_id": row.get("complaint_id", ""),
        "category": category,
        "priority": priority,
        "reason": reason,
        "flag": flag
    }


def batch_classify(input_path: str, output_path: str):
    """
    Read input CSV, classify each row, write results CSV.
    Must handle errors gracefully and not crash on bad rows.
    """
    results = []
    
    try:
        with open(input_path, mode='r', encoding='utf-8') as f:
            reader = csv.DictReader(f)
            for row in reader:
                try:
                    result = classify_complaint(row)
                    results.append(result)
                except Exception as e:
                    # Skip or log error for bad rows but don't crash
                    print(f"Error processing row {row.get('complaint_id', 'UNKNOWN')}: {e}")
                    results.append({
                        "complaint_id": row.get("complaint_id", ""),
                        "category": "Other",
                        "priority": "Low",
                        "reason": f"Processing error: {str(e)}",
                        "flag": "NEEDS_REVIEW"
                    })
    except FileNotFoundError:
        print(f"Input file {input_path} not found.")
        return

    # Write output
    fieldnames = ["complaint_id", "category", "priority", "reason", "flag"]
    try:
        with open(output_path, mode='w', encoding='utf-8', newline='') as f:
            writer = csv.DictWriter(f, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(results)
    except Exception as e:
        print(f"Failed to write results to {output_path}: {e}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="UC-0A Complaint Classifier")
    parser.add_argument("--input",  required=True, help="Path to test_[city].csv")
    parser.add_argument("--output", required=True, help="Path to write results CSV")
    args = parser.parse_args()
    batch_classify(args.input, args.output)
    print(f"Done. Results written to {args.output}")
